const demo=[{Region:"North",Category:"Electronics",Revenue:185000,Profit:37000,Quantity:120},{Region:"North",Category:"Home",Revenue:92000,Profit:16560,Quantity:90},{Region:"South",Category:"Electronics",Revenue:142000,Profit:25560,Quantity:100},{Region:"South",Category:"Home",Revenue:118000,Profit:21240,Quantity:130},{Region:"East",Category:"Electronics",Revenue:97000,Profit:19400,Quantity:80},{Region:"East",Category:"Home",Revenue:74000,Profit:11840,Quantity:85},{Region:"West",Category:"Electronics",Revenue:151000,Profit:30200,Quantity:105},{Region:"West",Category:"Home",Revenue:109000,Profit:19620,Quantity:110},{Region:"North",Category:"Grocery",Revenue:68000,Profit:8160,Quantity:180},{Region:"South",Category:"Grocery",Revenue:76000,Profit:9120,Quantity:195},{Region:"East",Category:"Grocery",Revenue:63000,Profit:7560,Quantity:160},{Region:"West",Category:"Grocery",Revenue:71000,Profit:9940,Quantity:175}];
let rows=[...demo];const $=id=>document.getElementById(id);const money=n=>"₹"+Math.round(n).toLocaleString("en-IN");function num(v){return Number(String(v).replace(/[^0-9.-]/g,""))||0}
function aggregate(field){const m={};rows.forEach(r=>{const k=r[field]??"Unknown";m[k]=(m[k]||0)+num(r.Revenue)});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function margin(field){const m={};rows.forEach(r=>{const k=r[field]??"Unknown";m[k]??={r:0,p:0};m[k].r+=num(r.Revenue);m[k].p+=num(r.Profit)});return Object.entries(m).map(([k,v])=>[k,v.p/v.r,v.r,v.p]).sort((a,b)=>b[1]-a[1])}
function renderTable(items,headers){$("evidenceTable").innerHTML='<table class="evidence-table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join("")+'</tr></thead><tbody>'+items.map(x=>'<tr>'+x.map(v=>'<td>'+v+'</td>').join("")+'</tr>').join("")+'</tbody></table>'}
function analyze(q){q=q.toLowerCase();if(q.includes("region")||q.includes("revenue")){const a=aggregate("Region"),top=a[0];$("answer").innerHTML='<h3>'+top[0]+' is currently the strongest revenue region.</h3><p>Computed from '+rows.length+' observed rows. '+top[0]+' contributes '+money(top[1])+' of revenue; the table shows the full evidence trail.</p>';renderTable(a.map(x=>[x[0],money(x[1])]),["Region","Revenue"]);return}
if(q.includes("margin")||q.includes("category")){const a=margin("Category"),top=a[0];$("answer").innerHTML='<h3>'+top[0]+' has the highest observed profit margin.</h3><p>Margin is calculated as profit ÷ revenue from the uploaded data, with no unsupported assumptions.</p>';renderTable(a.map(x=>[x[0],(x[1]*100).toFixed(1)+"%",money(x[2]),money(x[3])]),["Category","Margin","Revenue","Profit"]);return}
if(q.includes("price")||q.includes("10%")){$("answer").innerHTML='<h3>The simulator can test a price change before you act.</h3><p>Adjust the slider to see the transparent baseline-to-scenario change. This is a scenario, not a forecast guarantee.</p>';renderTable([["Baseline",money(total("Revenue")),money(total("Profit"))]],["Case","Revenue","Profit"]);return}
$("answer").innerHTML='<h3>Question needs an available business field.</h3><p>Try revenue by region, margin by category, or a price-change scenario. This guard prevents unsupported conclusions.</p>'}
function total(k){return rows.reduce((s,r)=>s+num(r[k]),0)}
function simulate(){const pct=Number($("price").value);const rev=total("Revenue"),profit=total("Profit"),newRev=rev*(1+pct/100),newProfit=profit*(1+pct/100);$("priceVal").textContent=(pct>=0?"+":"")+pct+"%";$("simRevenue").textContent=money(newRev);$("simProfit").textContent=money(newProfit);$("simDelta").textContent=(pct>=0?"+":"")+pct+"%";$("stressText").textContent=pct>15?"High sensitivity: a large price move should be validated with elasticity data before action.":pct<0?"Downside case: revenue and profit fall under the simple proportional assumption.":"Base case: proportional price/revenue assumption shown transparently."}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const heads=lines.shift().split(",").map(x=>x.trim());return lines.map(line=>{const vals=line.split(",");const o={};heads.forEach((h,i)=>o[h]=vals[i]?.trim()??"");return o}).filter(o=>Object.keys(o).length)}
function loadRows(data,name){rows=(data||[]).filter(r=>r&&Object.values(r).some(v=>String(v).trim()!==""));if(!rows.length){$("status").textContent="No rows found";return}const fields=Object.keys(rows[0]||{});$("meta").textContent=rows.length+" rows • "+fields.length+" fields";$("status").textContent=name+" loaded";analyze($("question").value);simulate()}
function loadFile(f){if(!f)return;const isXlsx=/\.(xlsx|xls)$/i.test(f.name);const reader=new FileReader();reader.onload=e=>{try{if(isXlsx){if(typeof XLSX==="undefined")throw new Error("Spreadsheet parser unavailable");const wb=XLSX.read(new Uint8Array(e.target.result),{type:"array"});const sheet=wb.Sheets[wb.SheetNames[0]];loadRows(XLSX.utils.sheet_to_json(sheet,{defval:""}),f.name)}else{loadRows(parseCSV(e.target.result),f.name)}}catch(err){$("status").textContent="Could not read file";$("answer").innerHTML="<h3>File could not be parsed.</h3><p>Use a CSV or XLSX with a header row and numeric Revenue/Profit columns for this demo.</p>"}};reader[isXlsx?"readAsArrayBuffer":"readAsText"](f)}
$("ask").onclick=()=>analyze($("question").value);document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{$("question").value=b.dataset.q;analyze(b.dataset.q)});$("price").oninput=simulate;$("loadDemo").onclick=()=>{rows=[...demo];$("meta").textContent=rows.length+" rows • 5 fields";$("status").textContent="Demo dataset ready";analyze($("question").value);simulate()};
$("file").onchange=e=>loadFile(e.target.files[0]);
$("drop").ondragover=e=>{e.preventDefault();$("drop").style.borderColor="#244c3a"};$("drop").ondrop=e=>{e.preventDefault();loadFile(e.dataTransfer.files[0]);};analyze($("question").value);simulate();